/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import servidor.view.TelaCadastroUsuario;

/**
 *
 * @author antonio.abnma
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPaneMenuPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGerencia = new javax.swing.JMenu();
        jMenuAddEditUsuario = new javax.swing.JMenuItem();
        jMenuRemoveUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuAddEditrSetor = new javax.swing.JMenuItem();
        jMenuRemoverSetor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuAddLocalidade = new javax.swing.JMenuItem();
        jMenuEditarLocalidade = new javax.swing.JMenuItem();
        jMenuRemoverLocalidade = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuGuiaLevantamentos = new javax.swing.JMenu();
        jMenuAddLevantamentos = new javax.swing.JMenuItem();
        jMenuEditLevantamento = new javax.swing.JMenuItem();
        jMenuRemoveLevantamento = new javax.swing.JMenuItem();
        jMenuImprimirLevantamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jDPaneMenuPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDPaneMenuPrincipalLayout = new javax.swing.GroupLayout(jDPaneMenuPrincipal);
        jDPaneMenuPrincipal.setLayout(jDPaneMenuPrincipalLayout);
        jDPaneMenuPrincipalLayout.setHorizontalGroup(
            jDPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jDPaneMenuPrincipalLayout.setVerticalGroup(
            jDPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jMenuGerencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/computer_key.png"))); // NOI18N
        jMenuGerencia.setMnemonic('G');
        jMenuGerencia.setText("GERÊNCIA");
        jMenuGerencia.setToolTipText("Gerencia os usuários do sistema.");

        jMenuAddEditUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_edit.png"))); // NOI18N
        jMenuAddEditUsuario.setText("Adicionar/Editar Usuário");
        jMenuAddEditUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuAddEditUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddEditUsuarioActionPerformed(evt);
            }
        });
        jMenuGerencia.add(jMenuAddEditUsuario);

        jMenuRemoveUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_delete.png"))); // NOI18N
        jMenuRemoveUsuario.setMnemonic('R');
        jMenuRemoveUsuario.setText("Remover Usuário");
        jMenuGerencia.add(jMenuRemoveUsuario);
        jMenuGerencia.add(jSeparator1);

        jMenuAddEditrSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/building_add.png"))); // NOI18N
        jMenuAddEditrSetor.setText("Adicionar/Editar Setor");
        jMenuGerencia.add(jMenuAddEditrSetor);

        jMenuRemoverSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/building_delete.png"))); // NOI18N
        jMenuRemoverSetor.setText("Remover Setor");
        jMenuGerencia.add(jMenuRemoverSetor);
        jMenuGerencia.add(jSeparator2);

        jMenuAddLocalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/map_add.png"))); // NOI18N
        jMenuAddLocalidade.setText("Adicionar Localidade");
        jMenuGerencia.add(jMenuAddLocalidade);

        jMenuEditarLocalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/map_edit.png"))); // NOI18N
        jMenuEditarLocalidade.setText("Editar Localidade");
        jMenuGerencia.add(jMenuEditarLocalidade);

        jMenuRemoverLocalidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/map_delete.png"))); // NOI18N
        jMenuRemoverLocalidade.setText("Remover Localidade");
        jMenuGerencia.add(jMenuRemoverLocalidade);
        jMenuGerencia.add(jSeparator3);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/door.png"))); // NOI18N
        jMenuSair.setText("SAIR");
        jMenuGerencia.add(jMenuSair);

        jMenuBar1.add(jMenuGerencia);

        jMenuGuiaLevantamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/page.png"))); // NOI18N
        jMenuGuiaLevantamentos.setMnemonic('L');
        jMenuGuiaLevantamentos.setText("LEVANTAMENTOS");

        jMenuAddLevantamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/page_add.png"))); // NOI18N
        jMenuAddLevantamentos.setText("Inserir Levantamento");
        jMenuGuiaLevantamentos.add(jMenuAddLevantamentos);

        jMenuEditLevantamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/page_edit.png"))); // NOI18N
        jMenuEditLevantamento.setText("Editar Levantamento");
        jMenuGuiaLevantamentos.add(jMenuEditLevantamento);

        jMenuRemoveLevantamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/page_delete.png"))); // NOI18N
        jMenuRemoveLevantamento.setText("Remover Levantamento");
        jMenuGuiaLevantamentos.add(jMenuRemoveLevantamento);

        jMenuImprimirLevantamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/printer.png"))); // NOI18N
        jMenuImprimirLevantamento.setText("Imprimir Levantamento");
        jMenuGuiaLevantamentos.add(jMenuImprimirLevantamento);

        jMenuBar1.add(jMenuGuiaLevantamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPaneMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPaneMenuPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAddEditUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddEditUsuarioActionPerformed
        TelaCadastroUsuario cadastroUsuario = new TelaCadastroUsuario();
        jDPaneMenuPrincipal.add(cadastroUsuario);
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuAddEditUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPaneMenuPrincipal;
    private javax.swing.JMenuItem jMenuAddEditUsuario;
    private javax.swing.JMenuItem jMenuAddEditrSetor;
    private javax.swing.JMenuItem jMenuAddLevantamentos;
    private javax.swing.JMenuItem jMenuAddLocalidade;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEditLevantamento;
    private javax.swing.JMenuItem jMenuEditarLocalidade;
    private javax.swing.JMenu jMenuGerencia;
    private javax.swing.JMenu jMenuGuiaLevantamentos;
    private javax.swing.JMenuItem jMenuImprimirLevantamento;
    private javax.swing.JMenuItem jMenuRemoveLevantamento;
    private javax.swing.JMenuItem jMenuRemoveUsuario;
    private javax.swing.JMenuItem jMenuRemoverLocalidade;
    private javax.swing.JMenuItem jMenuRemoverSetor;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
